name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v3

    - run: |
        rustup update ${{ matrix.rust }} &&
        rustup default ${{ matrix.rust }}

    - run: cargo test
    - run: cargo bench

  link:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        rustup update stable &&
        rustup default stable &&
        rustup component add rustfmt &&
        rustup component add clippy

    - run: cargo fmt -- --check
    - run: cargo clippy
