name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@v3

    - run: rustup update ${{ matrix.rust }}
    - run: rustup default ${{ matrix.rust }}

    - run: cargo test
    - run: cargo bench

  link:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup update stable
    - run: rustup default stable
    - run: rustup component add rustfmt clippy

    - run: cargo fmt -- --check
    - run: cargo clippy
